### ISSUE TITLE
A Better Name

### ISSUE THREAD

**Issue by ttymck** [ttymck/pycite#4]
`pycite` is intended as a tongue-in-cheek reference to the inspiration for this project: `h-index` and `altmetric`, dealing with bibliometric citations.

It might be a bit too narrow: the grand vision is a python package/distribution network analysis.

**Comment by mahmoud** [comment]
Hmm, I do enjoy the art of naming, so here are some out-loud thoughts.

First, we should think about the primary deliverable and its medium. Is it a pip installable library of some form? Is it a SQLite db made available for download? Is it an ongoing project, updated weekly or somesuch?

I do harbor some hopes that APA could grow into a collection of stock-market-style weighted indices, representing the best Python has to offer. One dimension of those could be an index on libraries. So we'd be able to say, "here are the most common libraries used by qt applications, or wsgi applications," or what have you.

Another angle on this trying to make a sort of [stackshare](https://stackshare.io/) for FOSS Python applications and libraries.

I'll think on it some more :)

**Comment by ttymck** [comment]
My original thought was a db for download; but it might as well go the next step and be a web api (much more vogue). I'm certainly game for it to be updated on a certain release schedule (perhaps yearly to avoid reader "fatigue").

In any case (however the results are distributed) the source code is always available here on github, and my hope is that the design is flexible enough to be extended by anyone who wishes to "dig a little deeper" as it were.

**Comment by ttymck** [comment]
As for the name: I had thought of the obvious `pynet`: python network analysis (with a mild allusion to skynet). But that looks to be well in use [here](https://pynet.twb-tech.com/).

Something referencing shipping manifests or library catalog might be appropriate. Indeed I'm not married to including `py` at all; which would allow this project to grow beyond this original intention.

**Comment by ttymck** [comment]
I quite like the tree analogy. I scoured wikipedia: from [dendrology](https://en.wikipedia.org/wiki/Dendrology), to [pedology](https://en.wikipedia.org/wiki/Pedology) and finally  [agrology](https://en.wikipedia.org/wiki/Agrology)

I propose: `pythagros` (python agrology)

Where agrology is the study of soil concerning crop production: `pythagros` will be the study of libraries (soil) concerning their use as application (crop) dependencies.

It also has a familiar pronunciation, close to "pythagoras". My only concern is it might be *too* close. But, I (we) must be realistic: this isn't the sort of project that would be used daily and **needs** a roll-off-the-tongue-name like `black` or `poetry`. I think `pythagros` might be good enough.

**Comment by mahmoud** [comment]
I like it actually! That said, I do what I usually do and strawpolled it a bit, and basically everyone heard Pythagoras. It's ok if it's a mouthful, but the ambiguity might be a blocker.

Without leaving the earth-y metaphor behind, since this is a *survey* of applications and their dependencies, I checked and [topygraph is available on PyPI](https://pypi.org/project/topygraph/). Like topographical survey. Has the "graph" element of it in there, too. 3 syllables is still a mouthful, but it's a little less ambiguous. Polled somewhat better, one person pointed out it almost worked like a sentence "to py graph". SEO is pretty open too. 

Not my best work quite, so I'll keep mulling on it in spare moments. :)

**Comment by ttymck** [comment]
That's pretty good. It maintains the python reference and generalizes nicely when pronounced "topigraph".

---- On Wed, 26 Dec 2018 15:11:01 -0800 notifications@github.com wrote ----

I like it actually! That said, I do what I usually do and strawpolled it a bit, and basically everyone heard Pythagoras. It's ok if it's a mouthful, but the ambiguity might be a blocker.

Without leaving the earth-y metaphor behind, since this is a survey of applications and their dependencies, I checked and topygraph is available on PyPI. Like topographical survey. Has the "graph" element of it in there, too. 3 syllables is still a mouthful, but it's a little less ambiguous. Polled somewhat better, one person pointed out it almost worked like a sentence "to py graph". SEO is pretty open too.

Not my best work quite, so I'll keep mulling on it in spare moments. :)

**Comment by ttymck** [comment]
tentatively jumping on it; this can be reopened with we manage to think of something even better
